# This is a basic workflow to help you get started with Actions

name: Prepare release

# Controls when the action will run. 
on:
#  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-version:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
      - uses: dotnet/nbgv@master
        id: nbgv
      - run: echo 'SemVer2=${{ steps.nbgv.outputs.SemVer2 }}'
  
